# a=open("people1-exercise.txt ","x")

# a=open("people1-exercise.txt ","w")
# a.write("rishabh - meerut"
# "imtiyaz - delhi"
# "nilima - cochin"
# "rati - shimla"
# "ayishah - delhi"
# "raghu - shimla"
# "aseer - kanpur"
# "karthikeyan - delhi"
# "salma - jaipur"
# "pankaj - delhi"
# "brijesh - delhi"
# "govind - delhi"
# "puneet - shimla"
# "siddhi - delhi"
# "suman - jaipur"
# "rajeev - shimla"
# "mohinder - delhi"
# "rajendra - jaipur"
# "priyanka - shimla"
# "neela - delhi"
# "sashi - jaipur"
# "sarika - delhi"
# "deepti - shimla"
# "harshad - delhi"
# "trishna - raipur"
# "pradeep - jaipur"
# "sekhar - delhi"
# "nand - delhi"
# "anoop - delhi"
# "balwinder - toky")
# print(a)

a=open("people1-exercise.txt ","w")
c=0
n=a.read("rishabh - meerut \n"
"imtiyaz - delhi"
"nilima - cochin"
"rati - shimla"
"ayishah - delhi"
"raghu - shimla"
"aseer - kanpur"
"karthikeyan - delhi"
"salma - jaipur"
"pankaj - delhi"
"brijesh - delhi"
"govind - delhi"
"puneet - shimla"
"siddhi - delhi"
"suman - jaipur"
"rajeev - shimla"
"mohinder - delhi"
"rajendra - jaipur"
"priyanka - shimla"
"neela - delhi"
"sashi - jaipur"
"sarika - delhi"
"deepti - shimla"
"harshad - delhi"
"trishna - raipur"
"pradeep - jaipur"
"sekhar - delhi"
"nand - delhi"
"anoop - delhi"
"balwinder - toky")
c=c+n
print(c)
